name: Unit Tests

on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  macos:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - run: COMPILER=clang++

      - name: Install Dependencies
        run: brew install cmake

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DUNIT_TEST=ON ..
          cmake --build .

      - name: Run Tests
        run: ./build/test/bcl_tests
